ice:
  build: ice
  command: | 
    -Djava.net.preferIPv4Stack=true
    -Djava.net.preferIPv4Addresses
    -Duser.timezone=<Your Timezone ie America/New_York>
    -Dice.s3AccessKeyId=<s3AccessKeyId>
    -Dice.s3SecretKey=<s3SecretKeyId>
    run-app
  volumes:
    - ./ice/assets/ice.properties:/opt/ice/src/java/ice.properties
nginx:
  build: nginx
  links:
    - ice:ice
oauth2_proxy:
  image: wingedkiwi/oauth2-proxy
  volumes:
    - ./oauth2_proxy/mount:/opt/oauth2-proxy/etc
  links:
    - nginx:nginx
  ports:
   - "4180:4180"
